import type { SkillDef } from '../../types/onboarding';

export const DEVOPS_SKILLS: SkillDef[] = [
  { name: 'Docker',          category: 'Tool' },
  { name: 'Kubernetes',      category: 'Tool' },
  { name: 'Terraform',       category: 'Tool' },
  { name: 'Ansible',         category: 'Tool' },
  { name: 'GitHub Actions',  category: 'Tool' },
  { name: 'Jenkins',         category: 'Tool' },
  { name: 'ArgoCD',          category: 'Tool' },
  { name: 'Linux',           category: 'Platform' },
  { name: 'Bash',            category: 'Language' },
  { name: 'Python',          category: 'Language' },
  { name: 'Prometheus',      category: 'Tool' },
  { name: 'Grafana',         category: 'Tool' },
  { name: 'ELK Stack',       category: 'Tool' },
  { name: 'Helm',            category: 'Tool' },
  { name: 'Nginx',           category: 'Tool' },
  { name: 'AWS',             category: 'Cloud' },
  { name: 'GCP',             category: 'Cloud' },
  { name: 'Azure',           category: 'Cloud' },
];

export const CLOUD_SKILLS: SkillDef[] = [
  { name: 'AWS',              category: 'Cloud' },
  { name: 'GCP',              category: 'Cloud' },
  { name: 'Azure',            category: 'Cloud' },
  { name: 'Terraform',        category: 'Tool' },
  { name: 'CloudFormation',   category: 'Tool' },
  { name: 'AWS Lambda',       category: 'Platform' },
  { name: 'ECS / EKS',       category: 'Platform' },
  { name: 'S3',               category: 'Platform' },
  { name: 'RDS',              category: 'Database' },
  { name: 'DynamoDB',         category: 'Database' },
  { name: 'VPC / Networking', category: 'Tool' },
  { name: 'IAM',              category: 'Tool' },
  { name: 'CDN / CloudFront', category: 'Cloud' },
  { name: 'Pulumi',           category: 'Tool' },
  { name: 'Docker',           category: 'Tool' },
  { name: 'Kubernetes',       category: 'Tool' },
];

export const DATA_ENGINEERING_SKILLS: SkillDef[] = [
  { name: 'Python',         category: 'Language' },
  { name: 'SQL',            category: 'Language' },
  { name: 'Apache Spark',   category: 'Framework' },
  { name: 'Airflow',        category: 'Tool' },
  { name: 'dbt',            category: 'Tool' },
  { name: 'Kafka',          category: 'Tool' },
  { name: 'Snowflake',      category: 'Database' },
  { name: 'BigQuery',       category: 'Database' },
  { name: 'Redshift',       category: 'Database' },
  { name: 'PostgreSQL',     category: 'Database' },
  { name: 'Hadoop',         category: 'Platform' },
  { name: 'Pandas',         category: 'Library' },
  { name: 'PySpark',        category: 'Library' },
  { name: 'AWS S3',         category: 'Cloud' },
  { name: 'Databricks',     category: 'Platform' },
];

export const ML_AI_SKILLS: SkillDef[] = [
  { name: 'Python',         category: 'Language' },
  { name: 'PyTorch',        category: 'Framework' },
  { name: 'TensorFlow',     category: 'Framework' },
  { name: 'Keras',          category: 'Library' },
  { name: 'scikit-learn',   category: 'Library' },
  { name: 'NumPy',          category: 'Library' },
  { name: 'Pandas',         category: 'Library' },
  { name: 'Hugging Face',   category: 'Library' },
  { name: 'LangChain',      category: 'Library' },
  { name: 'OpenAI API',     category: 'Platform' },
  { name: 'CUDA',           category: 'Platform' },
  { name: 'FastAPI',        category: 'Framework' },
  { name: 'MLflow',         category: 'Tool' },
  { name: 'Weights & Biases', category: 'Tool' },
  { name: 'Jupyter',        category: 'Tool' },
  { name: 'Docker',         category: 'Tool' },
];
