import type { SkillDef } from '../../types/onboarding';

export const WEB_FRONTEND_SKILLS: SkillDef[] = [
  { name: 'JavaScript',    category: 'Language' },
  { name: 'TypeScript',    category: 'Language' },
  { name: 'HTML5',         category: 'Language' },
  { name: 'CSS3',          category: 'Language' },
  { name: 'React',         category: 'Framework' },
  { name: 'Vue.js',        category: 'Framework' },
  { name: 'Angular',       category: 'Framework' },
  { name: 'Svelte',        category: 'Framework' },
  { name: 'Next.js',       category: 'Framework' },
  { name: 'Nuxt.js',       category: 'Framework' },
  { name: 'Tailwind CSS',  category: 'Framework' },
  { name: 'Bootstrap',     category: 'Framework' },
  { name: 'Redux',         category: 'Library' },
  { name: 'Zustand',       category: 'Library' },
  { name: 'React Query',   category: 'Library' },
  { name: 'Axios',         category: 'Library' },
  { name: 'Vite',          category: 'Tool' },
  { name: 'Webpack',       category: 'Tool' },
  { name: 'Jest',          category: 'Tool' },
  { name: 'Cypress',       category: 'Tool' },
  { name: 'Storybook',     category: 'Tool' },
  { name: 'Figma',         category: 'Tool' },
];

export const WEB_BACKEND_SKILLS: SkillDef[] = [
  { name: 'Node.js',       category: 'Framework' },
  { name: 'Python',        category: 'Language' },
  { name: 'Go',            category: 'Language' },
  { name: 'Java',          category: 'Language' },
  { name: 'Rust',          category: 'Language' },
  { name: 'PHP',           category: 'Language' },
  { name: 'Ruby',          category: 'Language' },
  { name: 'Express.js',    category: 'Framework' },
  { name: 'FastAPI',       category: 'Framework' },
  { name: 'Django',        category: 'Framework' },
  { name: 'Flask',         category: 'Framework' },
  { name: 'Spring Boot',   category: 'Framework' },
  { name: 'Laravel',       category: 'Framework' },
  { name: 'GraphQL',       category: 'Library' },
  { name: 'REST API',      category: 'Tool' },
  { name: 'PostgreSQL',    category: 'Database' },
  { name: 'MySQL',         category: 'Database' },
  { name: 'MongoDB',       category: 'Database' },
  { name: 'Redis',         category: 'Database' },
  { name: 'Docker',        category: 'Tool' },
  { name: 'Nginx',         category: 'Tool' },
  { name: 'JWT',           category: 'Tool' },
];

export const FULLSTACK_SKILLS: SkillDef[] = [
  { name: 'JavaScript',   category: 'Language' },
  { name: 'TypeScript',   category: 'Language' },
  { name: 'React',        category: 'Framework' },
  { name: 'Next.js',      category: 'Framework' },
  { name: 'Node.js',      category: 'Framework' },
  { name: 'Express.js',   category: 'Framework' },
  { name: 'Tailwind CSS', category: 'Framework' },
  { name: 'GraphQL',      category: 'Library' },
  { name: 'REST API',     category: 'Tool' },
  { name: 'PostgreSQL',   category: 'Database' },
  { name: 'MongoDB',      category: 'Database' },
  { name: 'Redis',        category: 'Database' },
  { name: 'Docker',       category: 'Tool' },
  { name: 'AWS',          category: 'Cloud' },
  { name: 'Vercel',       category: 'Cloud' },
  { name: 'Prisma',       category: 'Library' },
  { name: 'Jest',         category: 'Tool' },
];
